### ISSUE TITLE
the use of conjunctions in french

### ISSUE THREAD

**Issue by groenewege** [distantnative/relative-date#60]
Hi,

Native french speakers tell me that the conjunction "AND" is necessary in french.

The relative date for "2 months 3 weeks" should be "il y a 2 mois et 3 semaines" and not "il y a 2 mois 3 semaines".

Is this something that is possible right now or something that will be possible in the future ?

**Comment by distantnative** [comment]
It's not possible right now, but I'll have a look into adding a way for optional conjunctions (together with some optimization of the code in general)

**Comment by distantnative** [comment]
Added a first attempt: https://github.com/distantnative/relative-date#conjunctions

**Comment by groenewege** [comment]
Thank you !
That's great.
👍
