### ISSUE TITLE
Introduce function that can be called with a timestamp

### ISSUE THREAD

**Issue by JonasDoebertin** [distantnative/relative-date#63]
It would be awesome if the plugin would expose a helper function that takes a timestamp and (optionally) an array with args to generate the relative date string.

That way, one could use it with a pages `date()` and `modified()` properties as well as with any timestamp:

```php
echo relative($page->modified(), $args);
echo relative(1441270802, $args);
```

**Comment by distantnative** [comment]
:+1: will include one! will also help to streamline some of the current code!

**Comment by distantnative** [comment]
Added on the dev branch and will be included in the next release today:

```
<?php echo relativeDate($page->modified(), $args) ?>
``
