### ISSUE TITLE
Bahasa Indonesia (id)

### ISSUE THREAD

**Issue by chocochipz** [distantnative/relative-date#64]
Indonesian translation for Relative Date

**Comment by distantnative** [comment]
Can you help me translate the terms? Cause I really don't know how to speak it

**Comment by chocochipz** [comment]
Yeah sure.. That's what I'm for on here.
So from where I have to start? Please assist me.
Thank you!

**Comment by chocochipz** [comment]
Sorry, I'm newbie on GitHub.
So, I send the file on here.
Please see the attached file Bahasa Indonesia for Relative Date

[id.txt](https://github.com/distantnative/relative-date/files/36562/id.txt)

**Comment by chocochipz** [comment]
![sample-relative-date](https://cloud.githubusercontent.com/assets/3102479/11209693/5f6f7998-8d55-11e5-9186-ac30049a79c2.png)

**Comment by distantnative** [comment]
Looking good, will try to add it within the next days! thanks!

**Comment by chocochipz** [comment]
My pleasure.
Please let me know when need improve.
Thanks for the language label

**Comment by distantnative** [comment]
Added it to the develop branch. Thanks again!
