### ISSUE TITLE
Fuzzyness for days rather confusing

### ISSUE THREAD

**Issue by nocksock** [distantnative/relative-date#73]
Hi,

it'd be great if the fuzzyness for days, eg. `next monday` would rather bis `this monday`. Especially in german `next monday` would mean, usually when that monday is very close, the monday after the upcoming one. 

Is there a way to work around that? I can't simply change the translation, because it'd break the logic for the months, where `next` is the actual next month. 

I hope I got my point across, german can be rather confusing sometimes. :)

**Comment by distantnative** [comment]
I'm currently traveling in Mexico doing research for my PhD. I will be back on a laptop by the end of the month and then I'll look at this in detail - though I might not be able to support it as it aims rather to be applied in general to most languages.

**Comment by distantnative** [comment]
2.0.0 moved to be just a wrapper for the [Carbon library](http://carbon.nesbot.com/). Still thank you for your effort even though I could not live up to them 😞  👍

**Comment by distantnative** [comment]
2.0.0 moved to be just a wrapper for the [Carbon library](http://carbon.nesbot.com/). So there will not be any fuzzy expressions anymore.
